@startuml
!theme carbon-gray
'class Parameters_win'

/'
Pour l'instant la fenêtre principale a une liste de graph 
propre à chaque layout affiché
sur lesquels les données sont affichées et changées en fonction du type
En supposant donc que tout s'affiche sur un Multiplotwidget

Changement de paradigme
La fenetre principale a une liste des types d'affichages souhaitées
chaques affichage à une fenêtre qui lui est propre

avant 
dict_display {id: graph } 
MainWindow --> graph
class graph{
    multiplot
    plot
}

desormais
dict_display {id: <s> graph </s> type } 

'/

class MainWindow{
    - dict_data : {'name file' : MyDataLoader}
    - dict_layout {from Layout_Graph + dock}
    - dict_display {id:MyPlot}
    - load_multiple_file() {calls the correct dataloader for each type of file}
}

object dict_correspondance_format_dataloader

class MyDataLoader{
    - format : str
    - data : DataFram, xarray, hdf5, c3d
    - dict_ group : { 'group_path':{'var':[channel],'var2': [chanel]}}
    - path : str
    - open_file() {return data}
    - load_attribut(group) {update metadata}
    - get_group_var_channel() {return dict_group, update comboBox}
    - get_data(group,var,channel) {only way to access the data,return np.array}
    - save_data() {save processed signals}
    - save_attr() {save metadata}
}
note right
DataLoader are specific to the type of file
MyDataLoadernc, MyDataLoadercsv, MyDataLoaderc3d...
end note

class Layout_Graph{
    - list_layout() {return list of layout}
    - load_ui()
}
note left
Le Layout peut être personnalisé
et renvoie juste les emplacements 
où les graphes peuvent être affichés.

Cela permet aussi de rendre plus flexible 
les moyens de retourner les frames.
end note





MainWindow::dict_layout --> Layout_Graph
MainWindow::data  -> dict_correspondance_format_dataloader
dict_correspondance_format_dataloader --> MyDataLoader
MainWindow::dict_display  --->"*" OneGraph


class OneGraph{
    -id
    -parent
    -ui_graph
    -ui_parameters
    -layout_graph { button }
    -layout_parameters
    - oc_clickButton()
    - oc_comboBox_type_changed()
    -add_paramUi_to_layout()
    -add_graphUi_to_layout()
    -add_setting_to_param()
    -setPlot()
}

class Layout_Paramerters_Type{
    {inherits from QWidget}
    -layout_setting
    -loadUI()
}


class LayoutSettingfft{
    {inherits from Qwidget}
    -loadUI()
    -setInteractivity()
}

class LayoutSettingline{
    {inherits from Qwidget}
    -loadUI()
    -setInteractivity()
}

class PlotGeneral{
    {abstract}
    -id 
    -layout
    -layout_graph
    -parent

    -draw()
    -clear()

}

class PlotLine{

    -l {Layout ui}
    -function_name

}

class PlotFFT{

    -l {Layout ui}
    -function_name

}

OneGraph::ui_graph *-- PlotGeneral
OneGraph::ui_parameters *-- Layout_Paramerters_Type


pgMultiPlotWidget <|--PlotLine
pgMultiPlotWidget <|--PlotFFT
PlotGeneral <|--PlotFFT
PlotGeneral <|--PlotLine

PlotLine::l *-- LayoutSettingline
PlotFFT::l *-- LayoutSettingfft


@enduml
